### ISSUE TITLE
Texto en cuadro del Dash1

### ISSUE THREAD

**Issue by vguera** [mauleyzaola/iifeq#68]
Colocar este texto en el cuadro de texto del lado izquierdo del dash no 1.

Municipio: Querétaro
Población Total: 1,828,000
Población Estudiantil: 450,255
Mujeres: 221,888
Hombres: 228,367	

Total de inmuebles: 2,935
Total de centros de trabajo: 3,627
Preescolar: 1,550
Primaria: 1,501
Secundaria: 518
Centro de Atención Múltiple: 21
De apoyo a la educación especial: 37

Notas:
Incluye: Unidad de Servicios de Apoyo a la Educación Regular (USAER), Centro de Atención Psicopedagógica de Educación Preescolar (CAPEP), Centro de Recursos e Información para la Integración Educativa (CRIE), Centro de Recursos de Información y Orientación (CRIO), Unidades de Orientación al Público (UOP) y otras instalaciones de educación especial.
Incluye los tipos de servicio: general, indígena, secundaria técnica, telesecundaria, secundaria para trabajadores y centros de atención múltiple (CAM). Excluye los CT con modalidad Comunitaria (CONAFE).	
Alumnos: Población que en el momento del censo asiste regularmente a recibir educación básica o especial en una escuela.
Incluye a los alumnos de escuelas con tipo de servicio: general, indígena, secundaria técnica, telesecundaria, secundaria para trabajadores y a centros de apoyo a la educación especial (CAM). Excluye los CT con modalidad Comunitaria (CONAFE).

**Comment by mauleyzaola** [comment]
Esto ya fue... cerrado por falta de atencion 😂
